version: '3'

services:
  proxy:
    image: abiosoft/caddy:latest
    ports:
      - 80:80
      - 443:443
    networks:
      sowl:
        aliases:
          - proxy
    volumes:
      - caddy-ssl:/root/.caddy
      - caddy-configs:/usr/caddyfiles
    restart: on-failure
    command: ["--conf", "/usr/caddyfiles/Caddyfile", "--log", "stdout", "--agree=true"]
  
  skhus:
    image: skhusleepyowl/skhus-backend:latest
    cap_add:
      - SYS_ADMIN
    networks:
      sowl:
        aliases:
          - skhus
    restart: on-failure
   

networks:
  sowl:

volumes:
  caddy-configs:
  caddy-ssl: